testing/academia/academia/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
	url(r'^asistencia/', include('asistencia.urls')),
	url(r'^admin/logout',logout_then_login, name='logout'),
	url(r'^admin/', admin.site.urls),
	url(r'^accounts/login/',login,{'template_name':'register/index.html'}, name='login'),
    url(r'^logout/',logout_then_login, name='logout')
]

testing/academia/asistencia/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, logout_then_login
from . import views


app_name='asistencia'
urlpatterns = [
	url(r'^$', login_required(views.index), name='index'),
	url(r'(?P<estudiante_id>[0-9]+)/$', login_required(views.estudiante), name='estudiante'),
	url(r'^(?P<area_id>[\w\-]+)/pruebas/$',login_required(views.pruebas), name='pruebas'),
	url(r'^ranking',login_required(views.ranking), name='ranking'),
	url(r'^grupos',login_required(views.grupo),name='grupo'),
	url(r'^(?P<ranking_id>[0-9]+)/some_view/$', views.some_view,name='some_view'),
	url(r'^(?P<estudiante_id>[0-9]+)/some_asistencia/$',views.some_asistencia, name='some_asistencia'),
	url(r'^(?P<estudiante_id>[0-9]+)/some_reporte_alumno/$',views.some_reporte_alumno, name='some_reporte_alumno'),
	url(r'^(?P<area_id>[\w\-]+)/api/data/$',views.get_data,name='api-data'),
	url(r'^top/data/$',views.top_data,name='top_data'),
	url(r'^(?P<estudiante_id>[0-9]+)/api/estudiante/$',views.get_data_estudiante,name='get_data_estudiante'),
]	

"""
url(r'elegir_estudiante/$', views.Estudiante.as_view(), name='estudiante'),"""

testing/academia/asistencia/models.py
from django.db import models
from datetime import date

class Area(models.Model):
	area_tipo			= models.CharField(primary_key=True, max_length=100)
	def __str__(self):
		return self.area_tipo

class Grupo(models.Model):
	area 				= models.ForeignKey(Area, on_delete=models.CASCADE)
	codigo 				= models.CharField(max_length=100)
	numero_alumnos		= models.IntegerField(default=0)
	def __str__(self):
		return self.codigo


class Estudiante(models.Model):
	grupo 				= models.ForeignKey(Grupo, on_delete=models.CASCADE)
	nombre 				= models.CharField(max_length=100)
	apellido 			= models.CharField(max_length=100)
	fecha_nacimiento	= models.DateField()
	dni					= models.IntegerField(primary_key=True)
	def __str__(self):
		return str(self.dni)

class Ranking(models.Model):
	area 	 			= models.ForeignKey(Area,on_delete=models.CASCADE)
	fecha 				= models.DateField(default=date.today)
	promedio			= models.DecimalField(default=0, max_digits=6,decimal_places=3)
	def __str__(self):
		return str(self.fecha)

class Examen(models.Model):
	estudiante 			= models.ForeignKey(Estudiante, on_delete=models.CASCADE)
	ranking 			= models.ForeignKey(Ranking,on_delete=models.CASCADE)
	nota				= models.DecimalField(default=0,max_digits=6,decimal_places=3)

	class Meta:
		ordering=['nota']
	def __str__(self):
		return str(self.id)

class Permiso(models.Model):
	estudiante 			= models.ForeignKey(Estudiante, on_delete=models.CASCADE)
	fecha 				= models.DateField(default=date.today)
	detalle				= models.TextField(max_length=100)
	def __str__(self):
		return str(self.estudiante)+str(" ")+str(self.fecha)



class RegistroAsistencia(models.Model):
	class Meta:
		unique_together = (('estudiante', 'fecha'),)
	estudiante 			= models.ForeignKey(Estudiante,on_delete=models.CASCADE)
	fecha 				= models.DateField(default=date.today)
	registro_dia 		= models.BooleanField(default=False)
	registro_tarde 		= models.BooleanField(default=False)
	registro_seminario  = models.BooleanField(default=False)
	def __str__(self):
	   	return str(self.fecha)+str(" ")+str(self.estudiante)
	

testing/academia/asistencia/forms.py
from django import forms
from .models import *
class AsistenciaForm(forms.ModelForm):
	class Meta:
		model = RegistroAsistencia
		fields =[
			'estudiante',
			'fecha',
			'registro_dia',
			'registro_tarde',
			'registro_seminario'
		]
		widgets={
			'estudiante': forms.TextInput(attrs={'class':'input', 'style':'display:none'	}),
			'fecha': forms.TextInput(attrs={'class':'datepicker'	}),
			'registro_dia': forms.CheckboxInput (attrs={'class':'filled-in'	}),
			'registro_tarde': forms.CheckboxInput (attrs={'class':'filled-in'	}),
			'registro_seminario': forms.CheckboxInput (attrs={'class':'filled-in'	}),
		}

class AreaForm(forms.Form):
	area= forms.ModelChoiceField(queryset = Area.objects.all(),empty_label=None,required=False)

testing/academia/asistencia/views.py
from django.shortcuts import render,redirect
from django.http import Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from .models import *
from .forms import *
from datetime import datetime
from io import BytesIO
from reportlab.lib.colors import black
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import Paragraph,Table,TableStyle
#
 
def index(request):
	estudiantes_list = Estudiante.objects.all()
	query=request.GET.get('estudiante_id')

	if query:
		print("index_entro")
		estudiante = get_object_or_404(Estudiante,pk=query)
		return redirect('asistencia:estudiante',estudiante.dni)
	else:
		print("index_else")
		context ={
		'estudiantes_list':estudiantes_list,
		}
		return render(request, 'asistencia/index.html', context)


def estudiante(request, estudiante_id):
	estudiantes_list = Estudiante.objects.all()
	query=request.GET.get('estudiante_id')
	
	if query==None and estudiante_id:
		query=estudiante_id

	try:
		obj=RegistroAsistencia.objects.get(estudiante=query,fecha=datetime.now().strftime("%Y-%m-%d"))
	except RegistroAsistencia.DoesNotExist:
		registro=RegistroAsistencia.objects.create(estudiante=Estudiante.objects.get(pk=query))
		registro.save()
		obj=RegistroAsistencia.objects.get(estudiante=query,fecha=datetime.now().strftime("%Y-%m-%d"))
	print(query)
	print(estudiante_id)
	form=AsistenciaForm(request.POST or None,instance=obj)
	
	
	if request.method==("POST" or None):
		print("entro_post")
		estudiante_object = get_object_or_404(Estudiante,pk=query)
		context ={
			'estudiantes_list':estudiantes_list,
			'estudiante':estudiante_object,
			'form':form,
			}
		if form.is_valid():
			print("entro")
			form.save()
			form=AsistenciaForm()

		elif form.non_field_errors():
			data=request.POST.copy()
			fecha=data.get('fecha')
			data_estudiante=data.get('estudiante')
			registro=RegistroAsistencia.objects.get(estudiante=data_estudiante,fecha=fecha)
			data_dia=data.get('registro_dia')
			data_tarde=data.get('registro_tarde')
			data_seminario=data.get('registro_seminario')
			registro.registro_dia= True if data_dia=="on" else False
			registro.registro_tarde= True if data_tarde=="on" else False
			registro.registro_seminario= True if data_seminario=="on" else False	
			registro.save()	
		return render(request,'asistencia/estudiante.html',context)		
	if query:
		print("hello")
		estudiante = get_object_or_404(Estudiante,pk=query)
		context ={
			'estudiantes_list':estudiantes_list,
			'estudiante':estudiante,
			'form':form,
			}	
		return render(request,'asistencia/estudiante.html',context)
	else:
		context ={
		'estudiantes_list':estudiantes_list,
		}
		return render(request, 'asistencia/index.html', context)
	
		
def ranking(request):
		area_list=Area.objects.all()
		ranking_list=Ranking.objects.all()
		ranking_default=Ranking.objects.last()
		form=AreaForm(request.GET or None)
		query=request.GET.get('area')

		if query:
			ranking_list=Ranking.objects.filter(area=query)

		if 'ranking_get' in request.GET:
			query_ranking=request.GET.get('rankinglist_id')
			ranking_default=Ranking.objects.get(pk=query_ranking)
				
			print(query_ranking)

		if 'get_promedio' in request.GET:
			promedio_temp=0
			count=0
			query_ranking=request.GET.get('ranking_id')
			examenes=Examen.objects.filter(ranking=query_ranking)
			print(ranking_default.id)
			for examen in examenes:
				promedio_temp=promedio_temp+examen.nota
				count=count+1
			ranking_default=Ranking.objects.get(pk=query_ranking)
			ranking_default.promedio=(promedio_temp/count)
			ranking_default.save()
			print("entro_promedio")

		context={
			'ranking_list':ranking_list,
			'area_list':area_list,
			'form':form,
			'ranking_default':ranking_default,
		}
		return render(request,'asistencia/ranking.html',context)

		
def grupo(request):
		grupos_list=Grupo.objects.all()
		grupo_default=Grupo.objects.last()
		query=None
		form=AreaForm(request.GET or None)
		if form.is_valid():
			query=request.GET.get('area')
			grupos_list=Grupo.objects.filter(area=query)
		print(query)
		if 'grupo_get' in request.GET:
			query=request.GET.get('grupoid_list')
			print("grupo_get",query)
			grupo_default=Grupo.objects.get(pk=query)
		if 'set_alumnos' in request.GET:
			count=0
			query=request.GET.get('grupo_id')
			estudiantes=Estudiante.objects.filter(grupo=query)
			grupo_default=Grupo.objects.get(pk=query)
			grupo_default.numero_alumnos=estudiantes.count()
			grupo_default.save()
		context={
			'grupos_list':grupos_list,
			'form':form,
			'grupo_default':grupo_default,
		}
		return render(request,'asistencia/grupo.html',context)

def some_view(request,ranking_id):
	ranking=Ranking.objects.get(pk=ranking_id)
	examenes=Examen.objects.filter(ranking=ranking_id).order_by('-nota')

	print("Entro_some")
	# Create the HttpResponse object with the appropriate PDF headers.
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="reporte_ranking.pdf"'
	buffer= BytesIO()

	# Create the PDF object, using the response object as its "file."
	c = canvas.Canvas(buffer,pagesize=A4)

	#Header
	c.setLineWidth(.3)
	c.setFont('Helvetica',22)
	c.drawString(30,750,'Academia Municipal')

	c.setFont('Helvetica',12)
	c.drawString(30,735,'Ranking Semanal: N°' + str(ranking_id))

	c.setFont('Helvetica-Bold',15)
	c.drawString(30,710,'Area: '+str(ranking.area))

	c.setFont('Helvetica-Bold',15)
	c.drawString(410,710,'Promedio Total: ' +str(ranking.promedio))

	c.setFont('Helvetica-Bold',12)
	c.drawString(450,750,"Fecha: "+str(ranking.fecha))
	c.line(440,747,560,747)

	#table header
	styles 		= getSampleStyleSheet()
	styleBH 	= styles["Normal"]
	styleBH.alignment = TA_CENTER
	styleBH.fontSize  = 10

	posicion	= Paragraph('''#''',styleBH)
	numero 		= Paragraph('''DNI''', styleBH)
	alumno 		= Paragraph('''Alumno''',styleBH)
	nota 		= Paragraph('''Nota''',styleBH)
	data=[]
	data.append([posicion, numero, alumno, nota])

	styleN		= styles["BodyText"]
	styleN.alignment = TA_CENTER
	styleN.fontSize = 7

	high=650
	posicion_temp=1
	for examen in examenes:
		this_student = [str(posicion_temp),str(examen.estudiante.dni),str(examen.estudiante.apellido)+", "+str(examen.estudiante.nombre),str(examen.nota)]
		data.append(this_student)
		high=high-18
		posicion_temp=posicion_temp+1

	width, height = A4
	table = Table(data, colWidths=[1.9*cm, 3.61 * cm, 9.5 * cm, 4.0 * cm])	
	table.setStyle(TableStyle([
		('INNERGRID',(0,0),(-1,-1),0.25, black),
		('BOX',(0,0),(-1,-1),0.25, black),
		]))	
	table.wrapOn(c, width , height)
	table.drawOn(c, 30, high)
	c.showPage()

	c.save()
	pdf=buffer.getvalue()
	buffer.close()
	response.write(pdf)
	return response

def some_reporte_alumno(request,estudiante_id):
	estudiante=Estudiante.objects.get(pk=estudiante_id)
	registro_examenes=Examen.objects.filter(estudiante=estudiante_id).order_by('ranking__fecha')
	print("Entro_examen_reporte")
	# Create the HttpResponse object with the appropriate PDF headers.
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="reporte_examenes.pdf"'
	buffer= BytesIO()

	# Create the PDF object, using the response object as its "file."
	c = canvas.Canvas(buffer,pagesize=A4)

	#Header
	c.setLineWidth(.3)
	c.setFont('Helvetica',22)
	c.drawString(30,750,'Academia Municipal')

	c.setFont('Helvetica',12)
	c.drawString(30,735,'Registro de Examenes')

	c.setFont('Helvetica-Bold',15)
	c.drawString(30,710,'Estudiante: '+str(estudiante.apellido)+", "+str(estudiante.nombre))

	c.setFont('Helvetica',12)
	c.drawString(410,710,'Area: ' +str(estudiante.grupo.area))

	c.setFont('Helvetica-Bold',12)
	c.drawString(450,750,"DNI: "+str(estudiante.dni))
	c.line(440,747,560,747)

	styles 		= getSampleStyleSheet()
	styleBH 	= styles["Normal"]
	styleBH.alignment = TA_CENTER
	styleBH.fontSize  = 10

	numero		= Paragraph('''Examen N°''',styleBH)
	fecha 		= Paragraph('''Fecha''', styleBH)
	nota 		= Paragraph('''Nota''',styleBH)
	promedio	= Paragraph('''Promedio General del Ranking''',styleBH)
	data=[]
	data.append([numero,fecha,nota,promedio])

	styleN		= styles["BodyText"]
	styleN.alignment = TA_CENTER
	styleN.fontSize = 7

	high=650
	counter_num=1
	for examen in registro_examenes:
		this_registro=[str(counter_num), str(examen.ranking.fecha), str(examen.nota),str(examen.ranking.promedio)]
		data.append(this_registro)
		high=high-18
		counter_num=counter_num+1
		
	width, height = A4
	table = Table(data, colWidths=[2.5 *cm, 4.0 * cm, 4.0 * cm, 7.5 * cm])	
	table.setStyle(TableStyle([
		('INNERGRID',(0,0),(-1,-1),0.25, black),
		('BOX',(0,0),(-1,-1),0.25, black),
		]))	
	table.wrapOn(c, width , height)
	table.drawOn(c, 30, high)
	c.showPage()

	c.save()
	pdf=buffer.getvalue()
	buffer.close()
	response.write(pdf)
	return response




def some_asistencia(request, estudiante_id):
	estudiante=Estudiante.objects.get(pk=estudiante_id)
	registro_asistencia=RegistroAsistencia.objects.filter(estudiante=estudiante_id)
	print("Entro_asistencia")
	# Create the HttpResponse object with the appropriate PDF headers.
	response = HttpResponse(content_type='application/pdf')
	response['Content-Disposition'] = 'attachment; filename="reporte_asistencia.pdf"'
	buffer= BytesIO()

	# Create the PDF object, using the response object as its "file."
	c = canvas.Canvas(buffer,pagesize=A4)

	#Header
	c.setLineWidth(.3)
	c.setFont('Helvetica',22)
	c.drawString(30,750,'Academia Municipal')

	c.setFont('Helvetica',12)
	c.drawString(30,735,'Registro de Asistencia')

	c.setFont('Helvetica-Bold',15)
	c.drawString(30,710,'Estudiante: '+str(estudiante.apellido)+", "+str(estudiante.nombre))

	c.setFont('Helvetica',12)
	c.drawString(410,710,'Area: ' +str(estudiante.grupo.area))

testing/academia/asistencia/templates/asistencia/estudiante.html
{%extends 'asistencia/index.html'%}
{% load static %}

		{%block title%}Academia Municipal	{%endblock%}	

		{%block body%}
			<div class="row">
				<div class="col s6" style=" border-right: 1px solid #e0e0e0">
  					<div class="container section">
    					<form  method="get" action="" >
								<div class="input-field">
								<i class="material-icons prefix">search</i>
								<input type="text" name="estudiante_id" id="autocomplete-input" class="autocomplete" >
								<label for="autocomplete-input">Codigo de Alumno</label>
								<button  class="btn waves-effect waves-light" type="submit" value="elegir_estudiante">Buscar
									 <i class="material-icons right">send</i>
									</button>
								</div>
						</form>
					</div>
  				
			  		<div class="container divider"></div>
			  		<div class="container section">
			  			<div class=""><h4>Resultado de Examenes</h4></div>
						<ul id="dropdown2" class="dropdown-content">
						<li><a href="{% url 'asistencia:some_reporte_alumno' estudiante.dni %}">Reporte <i class="material-icons right">picture_as_pdf</i></a></li>
						<li><a class="modal-trigger" href="#modal1">Grafico<i class="material-icons right">show_chart</i></a>
							
						</li>
						</ul>
						<a class="btn dropdown-trigger" href="#!" data-target="dropdown2">Generar Reporte<i class="material-icons right">arrow_drop_down</i></a>
						<div id="modal1" class="modal">
								<div class="modal-content">
								<h4>Grafico</h4>
								  <canvas id="myChart"></canvas>
								</div>
							</div>
							<table>
								<thead>
								<tr>
									<th class="center-align">Numero</th>
									<th>Fecha</th>
									<th>Nota</th>
								</tr>
								</thead>

								<tbody>
									{%for examen in estudiante.examen_set.all%}
								<tr>
									<td class="center-align">{{forloop.counter}}</td>
									<td>{{examen.ranking.fecha}}</td>
									<td>{{examen.nota}}</td>
								</tr>
									{%endfor%}
								</tbody>
							</table>
 					</div>
				</div>
				<div class="col s6">
					<div class="container section">
					<div class=" card horizontal ">
						<div class="card-image estudiante">
							<i class="large material-icons center-align">account_circle</i>
						</div>
					<div class="card-stacked">
						<div class="card-content  ">
							<div class="row">
						      <div class="col s6 m6 l6 xl6">
						      	<ul>
						      		<li class="col s12 m12 l12 xl12">Nombre</li>
						      		<li class="col s12 m12 l12 xl12">Apellido</li>
						      		<li class="col s12 m12 l12 xl12">DNI</li>
						      	</ul>
						      </div>
						      <div class="col s6 m6 l6 xl6">
						      	<ul>
						      		<li class="col s12 m12 l12 xl12" >{{estudiante.nombre}}</li>
						      		<li class="col s12 m12 l12 xl12">{{estudiante.apellido}}</li>
						      		<li class="col s12 m12 l12 xl12">{{estudiante.dni}}</li>
						      	</ul>
						      </div>
						    </div>
						</div>						
					</div>
					</div>
					</div>

					<div class="container divider"></div>
					<div class="container section">
						 <h3 class="header">Registro de Asistencia</h3>
						  <div class="card-panel transparent">
							
							<div class="row">
								<h6>Ingrese la Fecha</h6>
					

						<form  method="POST" action="">
						{%csrf_token%}
			<div class="col s12">
				<label>
					{{form.estudiante}}
				</label>
			</div>
	<div class="col s1">
		<i class="small material-icons date ">date_range</i>
			</div>
	  	<div class="col s11">
	  		
 		 		{{form.fecha}}
			<label for="fecha" ></label>
		</div>
	
		<h6 class="header turno">Turno</h6>

		<div class="col s4">
			<label>
				{{form.registro_dia}}
				<span>Mañana</span>
			</label>
		</div>
		<div class="col s4">
			<label>
				{{form.registro_tarde}}
				<span>Tarde</span>
			</label>
		</div>
		<div class="col s4">
			<label>
				{{form.registro_seminario}}
				<span>Seminario</span>
			</label>
		</div>
		<div class="col s12 center-align">
			<button class="waves-effect waves-light btn registrar" type="submit">Registrar</button>
			<a  class="dropdown-trigger btn  waves-effect waves-light red lighten-2" data-target='dropdown1' style="margin-top:10px">Ver Todo</a>

			<ul id='dropdown1' class='dropdown-content'>
			<li><a href="{%url 'asistencia:some_asistencia' estudiante.dni %}"><i class="material-icons">picture_as_pdf</i>Reporte</a></li>
			<li><a href="{%url 'admin:asistencia_estudiante_change' estudiante.dni %}"><i class="material-icons">assignment_ind</i>Ver Pagina</a></li>
			</ul>
		</div>			


		</form>
						</div>
						  </div>
					</div>
				</div>

			</div>
	{%endblock%}	

	{%block script%}
	<script src="{% static 'asistencia/js/Chart.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'asistencia/js/materialize.min.js' %}"></script>
	<script type="text/javascript">
		document.addEventListener('DOMContentLoaded', function() {
	
		var elems_modal = document.querySelectorAll('.modal');
    	var instances = M.Modal.init(elems_modal);
		
    
		});
			var elems_dropdown = document.querySelectorAll('.dropdown-trigger');
    	var instances_dropdown = M.Dropdown.init(elems_dropdown, {
				onOpenStart: function () {
					setChart_examenes_alumno()
					console.log("I trigger as soon as the page is loaded");
				}
});

		$(document).ready(function(){
		
	
			$('.datepicker').datepicker({
				format:'yyyy-mm-dd',
				
			});
			$('.sidenav').sidenav();
			$('input.autocomplete').autocomplete({
				data: {
				{% for estudiant in estudiantes_list %}
					{{estudiant.dni}}:null,
				{% endfor %}
				},
    		});
		});
        var endpoint= "{%url 'asistencia:get_data_estudiante' estudiante.dni %}"
		var defaultData=[]
		var labels=[];
		$.ajax({
		    method: "GET",
		    url : endpoint,
		    success: function(data){
		        labels=data.labels
		        defaultData=data.default
		      
		    },

		    error: function(error_data){
		        console.log("error")
		        console.log(error_data)
		    }
		})
		function setChart_examenes_alumno(){
		    var ctx = document.getElementById('myChart').getContext('2d');
		    var myChart = new Chart(ctx, {
		    type: 'line',
		    data: {
		        labels: labels,
		        datasets: [{
		            label: 'Fecha-Nota',
		            data: defaultData,
		            backgroundColor: [
		                'rgba(255, 99, 132, 0.2)',
		                'rgba(54, 162, 235, 0.2)',
		                'rgba(255, 206, 86, 0.2)',
		                'rgba(75, 192, 192, 0.2)',
		                'rgba(153, 102, 255, 0.2)',
		                'rgba(255, 159, 64, 0.2)'
		            ],
		            borderColor: [
		                'rgba(255, 99, 132, 1)',
		                'rgba(54, 162, 235, 1)',
		                'rgba(255, 206, 86, 1)',
		                'rgba(75, 192, 192, 1)',
		                'rgba(153, 102, 255, 1)',
		                'rgba(255, 159, 64, 1)'
		            ],
		            borderWidth: 1
		        }]
		    },
		    options: {
		        scales: {
		            yAxes: [{
		                ticks: {
		                    beginAtZero: true
		                }
		            }]
		        }
		    }
		});
		}
	</script>	
	{%endblock%}



{%block script_base%}
{%endblock%}

testing/academia/asistencia/templates/asistencia/grupo.html
{%extends 'asistencia/index.html'%}
{% load static %}
{%block title%} Grupos {%endblock%}
{%block body%}
<div class="container row">
	<div class="col s3 l3 xl3 index">
		<div class="section">
			<form method="GET" >
				{{form.as_p}}
				<button class="waves-effect waves-light btn registrar" name="area_get" type="submit">Buscar</button>
			</form>
		</div>
		<div class="divider"></div>
		<div class="section">
			<form method="GET">
				<div class="input-field">		
						<select name="grupoid_list">
							<option value="" disabled selected>Grupo</option>
							{%for grupo in grupos_list %}
								<option value="{{grupo.id}}">{{grupo.codigo}}</option>
							{%endfor%}
						</select>
						<label>Grupo</label>
					</div>
				<button class="waves-effect waves-light btn registrar" name="grupo_get" type="submit">Buscar</button>
			</form>
		</div>
		<div class="divider"></div>
		<div class="section">
			<h5>Cambios</h5>
			<a class="btn waves-effect waves-light red lighten-2" href="{%url 'admin:asistencia_grupo_add' %}">Agregar</a>		
			<a class="btn waves-effect waves-light red lighten-2" href="{%url 'admin:asistencia_grupo_changelist' %}">Eliminar</a>
		</div>
	</div>
	<div class="col s9">
		<div class="section">
			<div class="row">
				<div class="col s4 ">
					<p class="center-align">GRUPO: {{grupo_default.codigo}}</p>
				</div>
				<div class="col s4">
					<p >AREA: {{grupo_default.area}}</p>
				</div>

				<div class="col s4">
					<form method="GET">
					 <input type="text" name="grupo_id" value="{{grupo_default.id}}" style="display:none">
					 <button style="margin-top: 8px" class="btn-flat tooltipped waves-effect waves-teal" data-position="bottom" data-tooltip="Ingresar Alumnos" type="submit" name="set_alumnos">
					 	Numero de Alumnos: {{grupo_default.numero_alumnos}}
				  	</button>
				    </form>    
				</div>

			</div>
			<h5 class="center-align"> Lista de Estudiantes</h5>
		</div>
		<div class="divider"></div>
		<div class="section">
			<table class="highlight">
				<thead>
					<tr>
						<th>DNI</th>
						<th>Nombre</th>
						<th>Fecha de Nacimiento</th>
					</tr>
				</thead>

				<tbody>
					{%for estudiante in grupo_default.estudiante_set.all%}
					<tr>
						<td>{{estudiante.dni}}</td>
						<td>{{estudiante.apellido}} , {{estudiante.nombre}}</td>
						<td>{{estudiante.fecha_nacimiento}}</td>				
					</tr>
					{%endfor%}
					
				</tbody>
			</table>
			
		</div>
	</div>
</div>
{%endblock%}


{%block script_base%}
{%endblock%}